name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restaurar dependências
      run: dotnet restore

    - name: Buildar solução
      run: dotnet build --no-restore --configuration Release

    - name: Rodar testes
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Instalar dotnet-ef
      run: dotnet tool install --global dotnet-ef

    - name: Adicionar dotnet-ef ao PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Validar migrations
      run: dotnet ef migrations script --project Eletro --output migration.sql

    - name: Salvar migration.sql como artefato
      uses: actions/upload-artifact@v3
      with:
        name: migration-sql
        path: migration.sql
